---
abstract: 'module for matching and manipulating company designators appended to company names'
author:
  - 'Gavin Carr <gavin@profound.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CompanyDesignator
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::ShareDir: 0
  List::MoreUtils: 0
  Mouse: 0
  Regexp::Assemble: 0
  Unicode::Normalize: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
